# In _config.yml
title: Computational Methods MATH0058 lecture notes
author: Timo Betcke, Erik Burman, Max Jensen
copyright: "2024"
logo: logo.png
sphinx:
  extra_extensions:
    - sphinx_proof
execute:
  execute_notebooks: off